/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DrawRouteImport } from './routes/draw'
import { Route as PlaybackRouteImport } from './routes/playback'
import { Route as LabRecordingRouteImport } from './routes/lab.recording'
import { Route as SessionSessionIdRouteImport } from './routes/session.$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawRoute = DrawRouteImport.update({
  id: '/draw',
  path: '/draw',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybackRoute = PlaybackRouteImport.update({
  id: '/playback',
  path: '/playback',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRecordingRoute = LabRecordingRouteImport.update({
  id: '/lab/recording',
  path: '/lab/recording',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionSessionIdRoute = SessionSessionIdRouteImport.update({
  id: '/session/$sessionId',
  path: '/session/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/draw': typeof DrawRoute
  '/playback': typeof PlaybackRoute
  '/lab/recording': typeof LabRecordingRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/draw': typeof DrawRoute
  '/playback': typeof PlaybackRoute
  '/lab/recording': typeof LabRecordingRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/draw': typeof DrawRoute
  '/playback': typeof PlaybackRoute
  '/lab/recording': typeof LabRecordingRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/draw' | '/playback' | '/lab/recording' | '/session/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/draw' | '/playback' | '/lab/recording' | '/session/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/draw'
    | '/playback'
    | '/lab/recording'
    | '/session/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DrawRoute: typeof DrawRoute
  PlaybackRoute: typeof PlaybackRoute
  LabRecordingRoute: typeof LabRecordingRoute
  SessionSessionIdRoute: typeof SessionSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draw': {
      id: '/draw'
      path: '/draw'
      fullPath: '/draw'
      preLoaderRoute: typeof DrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playback': {
      id: '/playback'
      path: '/playback'
      fullPath: '/playback'
      preLoaderRoute: typeof PlaybackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/recording': {
      id: '/lab/recording'
      path: '/lab/recording'
      fullPath: '/lab/recording'
      preLoaderRoute: typeof LabRecordingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$sessionId': {
      id: '/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/session/$sessionId'
      preLoaderRoute: typeof SessionSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DrawRoute: DrawRoute,
  PlaybackRoute: PlaybackRoute,
  LabRecordingRoute: LabRecordingRoute,
  SessionSessionIdRoute: SessionSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
